package com.valkylit.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AwardAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAwardAllPropertiesEquals(Award expected, Award actual) {
        assertAwardAutoGeneratedPropertiesEquals(expected, actual);
        assertAwardAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAwardAllUpdatablePropertiesEquals(Award expected, Award actual) {
        assertAwardUpdatableFieldsEquals(expected, actual);
        assertAwardUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAwardAutoGeneratedPropertiesEquals(Award expected, Award actual) {
        assertThat(expected)
            .as("Verify Award auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAwardUpdatableFieldsEquals(Award expected, Award actual) {
        assertThat(expected)
            .as("Verify Award relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAwardUpdatableRelationshipsEquals(Award expected, Award actual) {
        // empty method
    }
}
